name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
        id: go
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Migrations
        run: make migrate_up

      - name: Test
        run: make test

